// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2022-09-23 09:11:27.630363 +0800 CST m=+0.032377126

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/k8s_operation/deployment": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "获取deployment列表",
                "responses": {
                    "200": {
                        "description": "成功后返回",
                        "schema": {
                            "$ref": "#/definitions/model.DeploymentList"
                        }
                    }
                }
            }
        },
        "/k8s_operation/deployment/:deploymentName": {
            "get": {
                "summary": "获取特定deployment",
                "responses": {
                    "200": {
                        "description": "成功后返回deployment名",
                        "schema": {
                            "$ref": "#/definitions/model.DeploymentGet"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.DeploymentGet": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "replicas": {
                    "type": "integer"
                }
            }
        },
        "model.DeploymentList": {
            "type": "object",
            "properties": {
                "deploymentGetlist": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.DeploymentGet"
                    }
                },
                "err": {
                    "type": "error"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
